/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

// page class
/**
*  Object _page1_page()
*  @super _page
*  @constructor
*  @memberOf _page1_page 
*/
function _page1_page() {
}

//inherit _page
_page1_page.prototype = new _page("page1");

// widget assist
_page1_page.prototype.content1 = undefined;
_page1_page.prototype.gridcontainer = undefined;
_page1_page.prototype.row1 = undefined;
_page1_page.prototype.cell11 = undefined;
_page1_page.prototype.cell12 = undefined;
_page1_page.prototype.cell13 = undefined;
_page1_page.prototype.cell14 = undefined;
_page1_page.prototype.row2 = undefined;
_page1_page.prototype.cell21 = undefined;
_page1_page.prototype.cell22 = undefined;
_page1_page.prototype.cell23 = undefined;
_page1_page.prototype.cell24 = undefined;
_page1_page.prototype.row3 = undefined;
_page1_page.prototype.cell31 = undefined;
_page1_page.prototype.cell32 = undefined;
_page1_page.prototype.cell33 = undefined;
_page1_page.prototype.cell34 = undefined;
_page1_page.prototype.row4 = undefined;
_page1_page.prototype.cell41 = undefined;
_page1_page.prototype.cell42 = undefined;
_page1_page.prototype.cell43 = undefined;
_page1_page.prototype.cell44 = undefined;
_page1_page.prototype.heading1 = undefined;

// default widget event handler
_page1_page.prototype.gridcontainer_onswipe = function(event) {};

_page1_page.prototype.init_page = function(isStartPage, htmlPath, cssPath, managedCssPath) {
	this.htmlPath = htmlPath;
	this.cssPath = cssPath;
	this.managedCssPath = managedCssPath;
	this._init_page(function() {

		// widget assist (real object binding)

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.content1 = $("#page1 #content1");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.gridcontainer = $("#page1 #gridcontainer");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.row1 = $("#page1 #row1");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell11 = $("#page1 #cell11");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell12 = $("#page1 #cell12");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell13 = $("#page1 #cell13");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell14 = $("#page1 #cell14");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.row2 = $("#page1 #row2");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell21 = $("#page1 #cell21");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell22 = $("#page1 #cell22");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell23 = $("#page1 #cell23");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell24 = $("#page1 #cell24");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.row3 = $("#page1 #row3");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell31 = $("#page1 #cell31");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell32 = $("#page1 #cell32");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell33 = $("#page1 #cell33");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell34 = $("#page1 #cell34");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.row4 = $("#page1 #row4");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell41 = $("#page1 #cell41");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell42 = $("#page1 #cell42");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell43 = $("#page1 #cell43");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.cell44 = $("#page1 #cell44");

		/**
		 * @type jQueryObject
		 */
		_page1_page.prototype.heading1 = $("#page1 #heading1");

		// bind widget event handler
		_page1_page.prototype.gridcontainer.bind("swipe", function(event) { _page1_page.prototype.gridcontainer_onswipe(event); });

	}, isStartPage);

};
